
import { GoogleGenAI } from "@google/genai";
import { AspectRatio } from "../types";

export const generateImage = async (prompt: string, aspectRatio: AspectRatio): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please check your environment configuration.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio,
        }
      }
    });

    // Check for image in response candidates
    const candidate = response.candidates?.[0];
    if (!candidate?.content?.parts) {
      throw new Error("Invalid response format from Gemini API");
    }

    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error: any) {
    console.error("Image generation failed:", error);
    throw new Error(error.message || "An error occurred while generating your image.");
  }
};
